"""empty message

Revision ID: 003900943aac
Revises: 1609de0d4c1e
Create Date: 2021-05-05 10:33:26.988053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003900943aac'
down_revision = '1609de0d4c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'iridium_cep',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'iridium_cep',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
