"""empty message

Revision ID: 200fb3b4a38e
Revises: a024a2bb43b3
Create Date: 2020-07-25 12:04:46.153629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200fb3b4a38e'
down_revision = 'a024a2bb43b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devices', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'owner_id')
    # ### end Alembic commands ###
