"""empty message

Revision ID: 4312b3a5811a
Revises: 906b6257d264
Create Date: 2020-03-21 00:44:40.281486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4312b3a5811a'
down_revision = '906b6257d264'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('iridium_cep', sa.Integer(), nullable=True))
    op.add_column('messages', sa.Column('iridium_latitude', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('iridium_longitude', sa.Float(), nullable=True))
    op.add_column('messages', sa.Column('momsn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'momsn')
    op.drop_column('messages', 'iridium_longitude')
    op.drop_column('messages', 'iridium_latitude')
    op.drop_column('messages', 'iridium_cep')
    # ### end Alembic commands ###
