"""empty message

Revision ID: 534459703956
Revises: f33da7a7f3ef
Create Date: 2020-07-08 10:40:23.390970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534459703956'
down_revision = 'f33da7a7f3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'transmit_time',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'transmit_time',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
