"""empty message

Revision ID: 534459703956
Revises: f33da7a7f3ef
Create Date: 2020-07-08 10:40:23.390970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534459703956'
down_revision = 'f33da7a7f3ef'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'transmit_time')
    op.add_column('messages', sa.Column('transmit_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'transmit_time')
    op.add_column('messages', sa.Column('transmit_time', sa.String(), nullable=True))
    ### end Alembic commands ###
