"""empty message

Revision ID: 582d6c3b62c3
Revises: 
Create Date: 2020-03-16 16:08:56.329600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '582d6c3b62c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
