"""empty message

Revision ID: 906b6257d264
Revises: b888c864aa6f
Create Date: 2020-03-20 23:42:23.091798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906b6257d264'
down_revision = 'b888c864aa6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'time')
    # ### end Alembic commands ###
