"""empty message

Revision ID: aceb83a457ec
Revises: 534459703956
Create Date: 2020-07-09 10:27:41.840651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aceb83a457ec'
down_revision = '534459703956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender', sa.Integer()))
    op.create_foreign_key(None, 'messages', 'users', ['sender'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'sender')
    # ### end Alembic commands ###
