"""empty message

Revision ID: b18a0c2ca2e2
Revises: aceb83a457ec
Create Date: 2020-07-09 11:24:53.377575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18a0c2ca2e2'
down_revision = 'aceb83a457ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender_id', sa.Integer(), nullable=True))
    op.drop_constraint('messages_sender_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'])
    op.drop_column('messages', 'sender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sender', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_sender_fkey', 'messages', 'users', ['sender'], ['id'])
    op.drop_column('messages', 'sender_id')
    # ### end Alembic commands ###
